package TFC.WorldGen;

import net.minecraft.src.GenLayer;
import net.minecraft.src.IntCache;

public class GenLayerRiverMixTFC extends GenLayer
{
	private GenLayer field_35512_b;
	private GenLayer field_35513_c;

	public GenLayerRiverMixTFC(long par1, GenLayer par3GenLayer, GenLayer par4GenLayer)
	{
		super(par1);
		this.field_35512_b = par3GenLayer;
		this.field_35513_c = par4GenLayer;
	}

	/**
	 * Returns a list of integer values generated by this layer. These may be interpreted as temperatures, rainfall
	 * amounts, or biomeList[] indices based on the particular GenLayer subclass.
	 */
	public int[] getInts(int par1, int par2, int par3, int par4)
	{
		int[] layerBiomes = this.field_35512_b.getInts(par1, par2, par3, par4);
		int[] layerRivers = this.field_35513_c.getInts(par1, par2, par3, par4);
		int[] layerOut = IntCache.getIntCache(par3 * par4);

		for (int var8 = 0; var8 < par3 * par4; ++var8)
		{
			int b = layerBiomes[var8];
			int r = layerRivers[var8];

			if (layerBiomes[var8] == TFCBiome.ocean.biomeID)
            {
                layerOut[var8] = layerBiomes[var8];
            }
            else if (layerRivers[var8] >= 0)
            {
                if (layerBiomes[var8] == TFCBiome.icePlains.biomeID)
                {
                    layerOut[var8] = TFCBiome.frozenRiver.biomeID;
                }
                else if(layerBiomes[var8] == TFCBiome.swampland.biomeID)
                {
                    layerOut[var8] = TFCBiome.river2.biomeID;
                }
                else if(layerBiomes[var8] == TFCBiome.swamp2.biomeID)
                {
                    layerOut[var8] = TFCBiome.river3.biomeID;
                }
                else if(layerBiomes[var8] == TFCBiome.swamp3.biomeID)
                {
                    layerOut[var8] = TFCBiome.river4.biomeID;
                }
                else if(layerBiomes[var8] == TFCBiome.swamp4.biomeID)
                {
                    layerOut[var8] = TFCBiome.river5.biomeID;
                }
                else if(layerBiomes[var8] == TFCBiome.swamp5.biomeID)
                {
                    layerOut[var8] = TFCBiome.river6.biomeID;
                }
                else if(layerBiomes[var8] == TFCBiome.swamp6.biomeID)
                {
                    layerOut[var8] = TFCBiome.river7.biomeID;
                }
                else if(layerBiomes[var8] == TFCBiome.swamp7.biomeID)
                {
                    layerOut[var8] = TFCBiome.river8.biomeID;
                }
                else if(layerBiomes[var8] == TFCBiome.swamp9.biomeID)
                {
                    layerOut[var8] = TFCBiome.river10.biomeID;
                }
                else if(layerBiomes[var8] == TFCBiome.swamp10.biomeID)
                {
                    layerOut[var8] = TFCBiome.river11.biomeID;
                }
                else if(layerBiomes[var8] == TFCBiome.taiga.biomeID)
                {
                    layerOut[var8] = TFCBiome.river12.biomeID;
                }
                else if(layerBiomes[var8] == TFCBiome.taiga2.biomeID)
                {
                    layerOut[var8] = TFCBiome.river13.biomeID;
                }
                else if(layerBiomes[var8] == TFCBiome.taiga3.biomeID)
                {
                    layerOut[var8] = TFCBiome.river14.biomeID;
                }
                else if(layerBiomes[var8] == TFCBiome.taiga4.biomeID)
                {
                    layerOut[var8] = TFCBiome.river15.biomeID;
                }
                else if(layerBiomes[var8] == TFCBiome.taiga5.biomeID)
                {
                    layerOut[var8] = TFCBiome.river16.biomeID;
                }
                else if(layerBiomes[var8] == TFCBiome.taiga6.biomeID)
                {
                    layerOut[var8] = TFCBiome.river17.biomeID;
                }
                else if(layerBiomes[var8] == TFCBiome.taiga7.biomeID)
                {
                    layerOut[var8] = TFCBiome.river18.biomeID;
                }
                else if(layerBiomes[var8] == TFCBiome.taiga8.biomeID)
                {
                    layerOut[var8] = TFCBiome.river19.biomeID;
                }
                else if(layerBiomes[var8] == TFCBiome.taiga9.biomeID)
                {
                    layerOut[var8] = TFCBiome.river20.biomeID;
                }
                else if(layerBiomes[var8] == TFCBiome.taiga10.biomeID)
                {
                    layerOut[var8] = TFCBiome.river21.biomeID;
                }
                else if(layerBiomes[var8] == TFCBiome.forest.biomeID)
                {
                    layerOut[var8] = TFCBiome.river22.biomeID;
                }
                else if(layerBiomes[var8] == TFCBiome.forest2.biomeID)
                {
                    layerOut[var8] = TFCBiome.river23.biomeID;
                }
                else if(layerBiomes[var8] == TFCBiome.forest3.biomeID)
                {
                    layerOut[var8] = TFCBiome.river24.biomeID;
                }
                else if(layerBiomes[var8] == TFCBiome.forest4.biomeID)
                {
                    layerOut[var8] = TFCBiome.river25.biomeID;
                }
                else if(layerBiomes[var8] == TFCBiome.forest5.biomeID)
                {
                    layerOut[var8] = TFCBiome.river26.biomeID;
                }
                else if(layerBiomes[var8] == TFCBiome.forest6.biomeID)
                {
                    layerOut[var8] = TFCBiome.river27.biomeID;
                }
                else if(layerBiomes[var8] == TFCBiome.forest7.biomeID)
                {
                    layerOut[var8] = TFCBiome.river28.biomeID;
                }
                else if(layerBiomes[var8] == TFCBiome.forest8.biomeID)
                {
                    layerOut[var8] = TFCBiome.river29.biomeID;
                }
                else if(layerBiomes[var8] == TFCBiome.forest9.biomeID)
                {
                    layerOut[var8] = TFCBiome.river30.biomeID;
                }
                else if(layerBiomes[var8] == TFCBiome.plains.biomeID)
                {
                    layerOut[var8] = TFCBiome.river31.biomeID;
                }
                else if(layerBiomes[var8] == TFCBiome.plains2.biomeID)
                {
                    layerOut[var8] = TFCBiome.river32.biomeID;
                }
                else if(layerBiomes[var8] == TFCBiome.plains3.biomeID)
                {
                    layerOut[var8] = TFCBiome.river33.biomeID;
                }
                else if(layerBiomes[var8] == TFCBiome.plains4.biomeID)
                {
                    layerOut[var8] = TFCBiome.river34.biomeID;
                }
                else if(layerBiomes[var8] == TFCBiome.plains5.biomeID)
                {
                    layerOut[var8] = TFCBiome.river35.biomeID;
                }
                else if(layerBiomes[var8] == TFCBiome.plains6.biomeID)
                {
                    layerOut[var8] = TFCBiome.river36.biomeID;
                }
                else if(layerBiomes[var8] == TFCBiome.plains7.biomeID)
                {
                    layerOut[var8] = TFCBiome.river37.biomeID;
                }
                else if(layerBiomes[var8] == TFCBiome.plains8.biomeID)
                {
                    layerOut[var8] = TFCBiome.river38.biomeID;
                }
                else if(layerBiomes[var8] == TFCBiome.plains9.biomeID)
                {
                    layerOut[var8] = TFCBiome.river39.biomeID;
                }
                else if(layerBiomes[var8] == TFCBiome.plains10.biomeID)
                {
                    layerOut[var8] = TFCBiome.river40.biomeID;
                }
                else if(layerBiomes[var8] == TFCBiome.extremeHills.biomeID)
                {
                    layerOut[var8] = TFCBiome.extremeHills.biomeID;
                }
                else if(layerBiomes[var8] == TFCBiome.hills2.biomeID)
                {
                    layerOut[var8] = TFCBiome.hills2.biomeID;
                }
                else if(layerBiomes[var8] == TFCBiome.hills3.biomeID)
                {
                    layerOut[var8] = TFCBiome.hills3.biomeID;
                }
                else if(layerBiomes[var8] == TFCBiome.hills4.biomeID)
                {
                    layerOut[var8] = TFCBiome.hills4.biomeID;
                }
                else if(layerBiomes[var8] == TFCBiome.hills5.biomeID)
                {
                    layerOut[var8] = TFCBiome.hills5.biomeID;
                }
                else if(layerBiomes[var8] == TFCBiome.hills6.biomeID)
                {
                    layerOut[var8] = TFCBiome.hills6.biomeID;
                }
                else if(layerBiomes[var8] == TFCBiome.hills7.biomeID)
                {
                    layerOut[var8] = TFCBiome.hills7.biomeID;
                }
                else if(layerBiomes[var8] == TFCBiome.hills8.biomeID)
                {
                    layerOut[var8] = TFCBiome.hills8.biomeID;
                }
                else if(layerBiomes[var8] == TFCBiome.hills9.biomeID)
                {
                    layerOut[var8] = TFCBiome.hills9.biomeID;
                }
                else if(layerBiomes[var8] == TFCBiome.hills10.biomeID)
                {
                    layerOut[var8] = TFCBiome.hills10.biomeID;
                }
                else if(layerBiomes[var8] == TFCBiome.desert.biomeID)
                {
                    layerOut[var8] = TFCBiome.river51.biomeID;
                }
                else if(layerBiomes[var8] == TFCBiome.desert2.biomeID)
                {
                    layerOut[var8] = TFCBiome.river52.biomeID;
                }
                else if(layerBiomes[var8] == TFCBiome.desert3.biomeID)
                {
                    layerOut[var8] = TFCBiome.river53.biomeID;
                }
                else if(layerBiomes[var8] == TFCBiome.desert4.biomeID)
                {
                    layerOut[var8] = TFCBiome.river54.biomeID;
                }
                else if(layerBiomes[var8] == TFCBiome.desert5.biomeID)
                {
                    layerOut[var8] = TFCBiome.river55.biomeID;
                }
                else if(layerBiomes[var8] == TFCBiome.desert6.biomeID)
                {
                    layerOut[var8] = TFCBiome.river56.biomeID;
                }
                else if(layerBiomes[var8] == TFCBiome.desert7.biomeID)
                {
                    layerOut[var8] = TFCBiome.river57.biomeID;
                }
                else if(layerBiomes[var8] == TFCBiome.desert8.biomeID)
                {
                    layerOut[var8] = TFCBiome.river58.biomeID;
                }
                else if(layerBiomes[var8] == TFCBiome.desert9.biomeID)
                {
                    layerOut[var8] = TFCBiome.river59.biomeID;
                }
                else if(layerBiomes[var8] == TFCBiome.extremeHillsEdge.biomeID)
                {
                    layerOut[var8] = TFCBiome.extremeHillsEdge.biomeID;
                }
                else if(layerBiomes[var8] == TFCBiome.HillsEdge2.biomeID)
                {
                    layerOut[var8] = TFCBiome.HillsEdge2.biomeID;
                }
                else if(layerBiomes[var8] == TFCBiome.HillsEdge3.biomeID)
                {
                    layerOut[var8] = TFCBiome.HillsEdge3.biomeID;
                }
                else if(layerBiomes[var8] == TFCBiome.HillsEdge4.biomeID)
                {
                    layerOut[var8] = TFCBiome.HillsEdge4.biomeID;
                }
                else if(layerBiomes[var8] == TFCBiome.HillsEdge5.biomeID)
                {
                    layerOut[var8] = TFCBiome.HillsEdge5.biomeID;
                }
                else if(layerBiomes[var8] == TFCBiome.HillsEdge6.biomeID)
                {
                    layerOut[var8] = TFCBiome.HillsEdge6.biomeID;
                }
                else if(layerBiomes[var8] == TFCBiome.HillsEdge7.biomeID)
                {
                    layerOut[var8] = TFCBiome.HillsEdge7.biomeID;
                }
                else if(layerBiomes[var8] == TFCBiome.HillsEdge8.biomeID)
                {
                    layerOut[var8] = TFCBiome.HillsEdge8.biomeID;
                }
                else if(layerBiomes[var8] == TFCBiome.HillsEdge9.biomeID)
                {
                    layerOut[var8] = TFCBiome.HillsEdge9.biomeID;
                }
                else if(layerBiomes[var8] == TFCBiome.HillsEdge10.biomeID)
                {
                    layerOut[var8] = TFCBiome.HillsEdge10.biomeID;
                }
                else if (layerBiomes[var8] != TFCBiome.mushroomIsland.biomeID && layerBiomes[var8] != TFCBiome.mushroomIslandShore.biomeID)
                {
                    layerOut[var8] = layerRivers[var8];
                }
                else
                {
                    layerOut[var8] = TFCBiome.mushroomIslandShore.biomeID;
                }
			}
			else
			{
				layerOut[var8] = layerBiomes[var8];
			}

			//            if(layerOut[var8] == 7)
				//            	System.out.println("Made a Normal River");
		}

		return layerOut;
	}

	/**
	 * Initialize layer's local worldGenSeed based on its own baseSeed and the world's global seed (passed in as an
	 * argument).
	 */
	public void initWorldGenSeed(long par1)
	{
		this.field_35512_b.initWorldGenSeed(par1);
		this.field_35513_c.initWorldGenSeed(par1);
		super.initWorldGenSeed(par1);
	}
}
