package com.bioxx.tfc.WorldGen.GenLayers;

import net.minecraft.world.gen.layer.GenLayer;
import net.minecraft.world.gen.layer.IntCache;

public class GenLayerFuzzyZoomTFC extends GenLayerTFC
{
	public GenLayerFuzzyZoomTFC(long par1, GenLayer par3GenLayer)
	{
		super(par1);
		super.parent = (GenLayerTFC) par3GenLayer;
	}

	/**
	 * Returns a list of integer values generated by this layer. These may be interpreted as temperatures, rainfall
	 * amounts, or biomeList[] indices based on the particular GenLayer subclass.
	 */
	@Override
	public int[] getInts(int x, int z, int xSize, int zSize)
	{
		int xMin = x >> 1;
		int zMin = z >> 1;
		int xMax = (xSize >> 1) + 3;
		int zMax = (zSize >> 1) + 3;
		int[] parentNoise = this.parent.getInts(xMin, zMin, xMax, zMax);
		int[] cache = IntCache.getIntCache(xMax * 2 * zMax * 2);
		int var11 = xMax << 1;
		int var13;

		for (int k = 0; k < zMax - 1; ++k)
		{
			var13 = k << 1;
			int var14 = var13 * var11;
			int var15 = parentNoise[0 + (k + 0) * xMax];
			int var16 = parentNoise[0 + (k + 1) * xMax];

			for (int i = 0; i < xMax - 1; ++i)
			{
				this.initChunkSeed(i + xMin << 1, k + zMin << 1);
				int var18 = parentNoise[i + 1 + (k + 0) * xMax];
				int var19 = parentNoise[i + 1 + (k + 1) * xMax];
				cache[var14] = var15;
				cache[var14++ + var11] = this.choose(var15, var16);
				cache[var14] = this.choose(var15, var18);
				cache[var14++ + var11] = this.choose(var15, var18, var16, var19);
				var15 = var18;
				var16 = var19;
			}
		}

		int[] newCache = IntCache.getIntCache(xSize * zSize);

		for (var13 = 0; var13 < zSize; ++var13)
			System.arraycopy(cache, (var13 + (z & 1)) * (xMax << 1) + (x & 1), newCache, var13 * xSize, xSize);

		return newCache;
	}

	/**
	 * randomly choose between the two args
	 */
	protected int choose(int par1, int par2)
	{
		return this.nextInt(2) == 0 ? par1 : par2;
	}

	/**
	 * randomly choose between the four args
	 */
	protected int choose(int par1, int par2, int par3, int par4)
	{
		int var5 = this.nextInt(4);
		return var5 == 0 ? par1 : (var5 == 1 ? par2 : (var5 == 2 ? par3 : par4));
	}
}
