package com.bioxx.tfc.WorldGen.GenLayers;

import net.minecraft.world.gen.layer.GenLayer;
import net.minecraft.world.gen.layer.IntCache;

public class GenLayerRiverInitTFC extends GenLayerTFC
{
	public GenLayerRiverInitTFC(long par1, GenLayer par3GenLayer)
	{
		super(par1);
		this.parent = (GenLayerTFC) par3GenLayer;
	}

	/**
	 * Returns a list of integer values generated by this layer. These may be interpreted as temperatures, rainfall
	 * amounts, or biomeList[] indices based on the particular GenLayer subclass.
	 */
	public int[] getInts(int x, int z, int maxX, int maxZ)
	{
		int[] noise = this.parent.getInts(x, z, maxX, maxZ);
		int[] cache = IntCache.getIntCache(maxX * maxZ);

		for (int i = 0; i < maxZ; ++i)
		{
			for (int k = 0; k < maxX; ++k)
			{
				this.initChunkSeed((long)(k + x), (long)(i + z));
				cache[k + i * maxX] = noise[k + i * maxX] > 0 ? this.nextInt(2) + 2 : 0;
			}
		}
		return cache;
	}
}
