package com.bioxx.tfc.WorldGen.GenLayers;

import net.minecraft.world.biome.BiomeGenBase;
import net.minecraft.world.gen.layer.IntCache;

public class GenLayerRareBiomeTFC extends GenLayerTFC
{
	public GenLayerRareBiomeTFC(long p_i45478_1_, GenLayerTFC p_i45478_3_)
	{
		super(p_i45478_1_);
		this.parent = p_i45478_3_;
	}

	/**
	 * Returns a list of integer values generated by this layer. These may be interpreted as temperatures, rainfall
	 * amounts, or biomeList[] indices based on the particular GenLayer subclass.
	 */
	@Override
	public int[] getInts(int par1, int par2, int par3, int par4)
	{
		int[] aint = this.parent.getInts(par1 - 1, par2 - 1, par3 + 2, par4 + 2);
		int[] aint1 = IntCache.getIntCache(par3 * par4);

		for (int i1 = 0; i1 < par4; ++i1)
		{
			for (int j1 = 0; j1 < par3; ++j1)
			{
				this.initChunkSeed(j1 + par1, i1 + par2);
				int k1 = aint[j1 + 1 + (i1 + 1) * (par3 + 2)];

				if (this.nextInt(57) == 0)
				{
					if (k1 == BiomeGenBase.plains.biomeID)
					{
						aint1[j1 + i1 * par3] = BiomeGenBase.plains.biomeID + 128;
					}
					else
					{
						aint1[j1 + i1 * par3] = k1;
					}
				}
				else
				{
					aint1[j1 + i1 * par3] = k1;
				}
			}
		}

		return aint1;
	}
}
