package com.bioxx.tfc.WorldGen.GenLayers;

import net.minecraft.world.gen.layer.GenLayer;
import net.minecraft.world.gen.layer.IntCache;

public class GenLayerAddIslandTFC extends GenLayerTFC
{
	public GenLayerAddIslandTFC(long par1, GenLayer par3GenLayer)
	{
		super(par1);
		this.parent = (GenLayerTFC) par3GenLayer;
	}

	/**
	 * Returns a list of integer values generated by this layer. These may be interpreted as temperatures, rainfall
	 * amounts, or biomeList[] indices based on the particular GenLayer subclass.
	 */
	@Override
	public int[] getInts(int x, int z, int xSize, int zSize)
	{
		int xm1 = x - 1;
		int zm1 = z - 1;
		int xMax = xSize + 2;
		int zMax = zSize + 2;
		int[] noise = this.parent.getInts(xm1, zm1, xMax, zMax);
		int[] cache = IntCache.getIntCache(xSize * zSize);

		for (int k = 0; k < zSize; ++k)
		{
			for (int i = 0; i < xSize; ++i)
			{
				int var13 = noise[i + 0 + (k + 0) * xMax];
				int var14 = noise[i + 2 + (k + 0) * xMax];
				int var15 = noise[i + 0 + (k + 2) * xMax];
				int var16 = noise[i + 2 + (k + 2) * xMax];
				int var17 = noise[i + 1 + (k + 1) * xMax];
				this.initChunkSeed(i + x, k + z);

				if (var17 == 0 && (var13 != 0 || var14 != 0 || var15 != 0 || var16 != 0))
				{
					int var18 = 1;
					int var19 = 1;

					if (var13 != 0 && this.nextInt(var18++) == 0)
						var19 = var13;

					if (var14 != 0 && this.nextInt(var18++) == 0)
						var19 = var14;

					if (var15 != 0 && this.nextInt(var18++) == 0)
						var19 = var15;

					if (var16 != 0 && this.nextInt(var18++) == 0)
						var19 = var16;

					if (this.nextInt(3) == 0)
						cache[i + k * xSize] = var19;
					else
						cache[i + k * xSize] = 0;
				}
				else if (var17 > 0 && (var13 == 0 || var14 == 0 || var15 == 0 || var16 == 0))
				{
					if (this.nextInt(5) == 0)
						cache[i + k * xSize] = 0;
					else
						cache[i + k * xSize] = var17;
				}
				else
				{
					cache[i + k * xSize] = var17;
				}
			}
		}
		return cache;
	}
}
