package com.bioxx.tfc.WorldGen.GenLayers;

import net.minecraft.world.gen.layer.IntCache;

import com.bioxx.tfc.WorldGen.TFCBiome;

public class GenLayerRemoveOrphanRiver extends GenLayerTFC
{
	int[] layerBiomes;
	int[] layerOut;
	int xn = 0;
	int xp = 0;
	int zn = 0;
	int zp = 0;

	public GenLayerRemoveOrphanRiver(long par1, GenLayerTFC parent)
	{
		super(par1);
		this.parent = parent;
	}

	/**
	 * Returns a list of integer values generated by this layer. These may be interpreted as temperatures, rainfall
	 * amounts, or biomeList[] indices based on the particular GenLayer subclass.
	 */
	@Override
	public int[] getInts(int x, int z, int xSize, int zSize)
	{
		layerBiomes = this.parent.getInts(x, z, xSize, zSize);
		layerOut = IntCache.getIntCache(xSize * zSize);

		for (int index = 0; index < xSize * zSize; ++index)
		{
			int b = layerBiomes[index];

			xn = index-1;
			xp = index+1;
			zn = index-zSize;
			zp = index+zSize;

			if(layerBiomes[index] == TFCBiome.river.biomeID)
			{
				int count = 0;
				int id = 0;
				if(inBounds(xn, layerBiomes))
				{
					if(layerBiomes[xn] != TFCBiome.river.biomeID)
					{
						count++;
						id = layerBiomes[xn];
					}
				}
				else
					count++;

				if(inBounds(xp, layerBiomes))
				{
					if(layerBiomes[xp] != TFCBiome.river.biomeID)
					{
						count++;
						id = layerBiomes[xp];
					}
				}
				else
					count++;

				if(inBounds(zn, layerBiomes))
				{
					if(layerBiomes[zn] != TFCBiome.river.biomeID)
					{
						count++;
						id = layerBiomes[zn];
					}
				}
				else
					count++;

				if(inBounds(zp, layerBiomes))
				{
					if(layerBiomes[zp] != TFCBiome.river.biomeID)
					{
						count++;
						id = layerBiomes[zp];
					}
				}
				else
					count++;

				if(count == 4)
					layerOut[index] = id; 
				else layerOut[index] = layerBiomes[index];
			}
			else layerOut[index] = layerBiomes[index];
		}
		return layerOut;
	}

	public boolean inBounds(int index, int[] array)
	{
		if(index < array.length && index >= 0)
			return true;
		return false;
	}
}
