package com.bioxx.tfc.WorldGen.GenLayers;

import net.minecraft.world.biome.BiomeGenBase;
import net.minecraft.world.gen.layer.GenLayer;
import net.minecraft.world.gen.layer.IntCache;

public class GenLayerShoreTFC extends GenLayerTFC
{
	public GenLayerShoreTFC(long par1, GenLayer par3GenLayer)
	{
		super(par1);
		this.parent = (GenLayerTFC) par3GenLayer;
	}

	/**
	 * Returns a list of integer values generated by this layer. These may be interpreted as temperatures, rainfall
	 * amounts, or biomeList[] indices based on the particular GenLayer subclass.
	 */
	@Override
	public int[] getInts(int par1, int par2, int par3, int par4)
	{
		int[] var5 = this.parent.getInts(par1 - 1, par2 - 1, par3 + 2, par4 + 2);
		int[] var6 = IntCache.getIntCache(par3 * par4);

		for (int var7 = 0; var7 < par4; ++var7)
		{
			for (int var8 = 0; var8 < par3; ++var8)
			{
				this.initChunkSeed(var8 + par1, var7 + par2);
				int var9 = var5[var8 + 1 + (var7 + 1) * (par3 + 2)];
				int var10;
				int var11;
				int var12;
				int var13;

				if (var9 != BiomeGenBase.ocean.biomeID && var9 != BiomeGenBase.river.biomeID && var9 != BiomeGenBase.swampland.biomeID)
				{
					var10 = var5[var8 + 1 + (var7 + 1 - 1) * (par3 + 2)];
					var11 = var5[var8 + 1 + 1 + (var7 + 1) * (par3 + 2)];
					var12 = var5[var8 + 1 - 1 + (var7 + 1) * (par3 + 2)];
					var13 = var5[var8 + 1 + (var7 + 1 + 1) * (par3 + 2)];

					if (var10 != BiomeGenBase.ocean.biomeID && var11 != BiomeGenBase.ocean.biomeID && var12 != BiomeGenBase.ocean.biomeID && var13 != BiomeGenBase.ocean.biomeID)
						var6[var8 + var7 * par3] = var9;
					else
						var6[var8 + var7 * par3] = BiomeGenBase.beach.biomeID;
				}
				/*else if (var9 == BiomeGenBase.HighHills.biomeID)
				{
					var10 = var5[var8 + 1 + (var7 + 1 - 1) * (par3 + 2)];
					var11 = var5[var8 + 1 + 1 + (var7 + 1) * (par3 + 2)];
					var12 = var5[var8 + 1 - 1 + (var7 + 1) * (par3 + 2)];
					var13 = var5[var8 + 1 + (var7 + 1 + 1) * (par3 + 2)];

					if (var10 == BiomeGenBase.HighHills.biomeID && var11 == BiomeGenBase.HighHills.biomeID && var12 == BiomeGenBase.HighHills.biomeID && var13 == BiomeGenBase.HighHills.biomeID)
						var6[var8 + var7 * par3] = var9;
					else
						var6[var8 + var7 * par3] = BiomeGenBase.HighHillsEdge.biomeID;
				}
				else if (var9 == BiomeGenBase.Mountains.biomeID)
				{
					var10 = var5[var8 + 1 + (var7 + 1 - 1) * (par3 + 2)];
					var11 = var5[var8 + 1 + 1 + (var7 + 1) * (par3 + 2)];
					var12 = var5[var8 + 1 - 1 + (var7 + 1) * (par3 + 2)];
					var13 = var5[var8 + 1 + (var7 + 1 + 1) * (par3 + 2)];

					if (var10 == BiomeGenBase.Mountains.biomeID && var11 == BiomeGenBase.Mountains.biomeID && var12 == BiomeGenBase.Mountains.biomeID && var13 == BiomeGenBase.Mountains.biomeID)
						var6[var8 + var7 * par3] = var9;
					else
						var6[var8 + var7 * par3] = BiomeGenBase.MountainsEdge.biomeID;
				}*/
				else
				{
					var6[var8 + var7 * par3] = var9;
				}
			}
		}
		return var6;
	}
}
