package TFC.WorldGen.GenLayers;

import TFC.WorldGen.DataLayer;
import net.minecraft.src.BiomeGenBase;
import net.minecraft.src.GenLayer;
import net.minecraft.src.IntCache;
import net.minecraft.src.WorldType;

public class GenLayerEVTTypes extends GenLayerTFC
{
	public static DataLayer[] biomeArray = new DataLayer[] {DataLayer.EVT_0_125,DataLayer.EVT_0_25,DataLayer.EVT_0_5,DataLayer.EVT_1,
		DataLayer.EVT_2,DataLayer.EVT_4,DataLayer.EVT_8,DataLayer.EVT_16};

	/** this sets all the biomes that are allowed to appear in the overworld */
	private DataLayer[] allowedBiomes;

	public GenLayerEVTTypes(long par1, GenLayer par3GenLayer, WorldType par4WorldType)
	{
		super(par1);
		this.allowedBiomes = biomeArray;
		this.parent = (GenLayerTFC) par3GenLayer;
	}

	/**
	 * Returns a list of integer values generated by this layer. These may be interpreted as temperatures, rainfall
	 * amounts, or biomeList[] indices based on the particular GenLayer subclass.
	 */
	public int[] getInts(int par1, int par2, int par3, int par4)
	{
		int[] var5 = this.parent.getInts(par1, par2, par3, par4);
		int[] var6 = IntCache.getIntCache(par3 * par4);

		for (int var7 = 0; var7 < par4; ++var7)
		{
			for (int var8 = 0; var8 < par3; ++var8)
			{
				this.initChunkSeed((long)(var8 + par1), (long)(var7 + par2));
				int var9 = var5[var8 + var7 * par3];

				if (var9 == 0)
				{
					var6[var8 + var7 * par3] = DataLayer.EVT_0_5.ID;
				}
				else
				{
					var6[var8 + var7 * par3] = this.allowedBiomes[this.nextInt(this.allowedBiomes.length)].ID;
				}
			}
		}

		return var6;
	}
}
