package com.bioxx.tfc.WorldGen.GenLayers.DataLayers.Rain;

import net.minecraft.world.gen.layer.GenLayer;
import net.minecraft.world.gen.layer.IntCache;

import com.bioxx.tfc.WorldGen.GenLayers.GenLayerTFC;

public class GenLayerAddRain extends GenLayerTFC
{
	public GenLayerAddRain(long par1, GenLayer par3GenLayer)
	{
		super(par1);
		this.parent = (GenLayerTFC) par3GenLayer;
	}

	/**
	 * Returns a list of integer values generated by this layer. These may be interpreted as temperatures, rainfall
	 * amounts, or biomeList[] indices based on the particular GenLayer subclass.
	 */
	@Override
	public int[] getInts(int par1, int par2, int par3, int par4)
	{
		int var5 = par1 - 1;
		int var6 = par2 - 1;
		int var7 = par3 + 2;
		int var8 = par4 + 2;
		int[] var9 = this.parent.getInts(var5, var6, var7, var8);
		int[] outCache = IntCache.getIntCache(par3 * par4);

		for (int var11 = 0; var11 < par4; ++var11)
		{
			for (int var12 = 0; var12 < par3; ++var12)
			{
				int var13 = var9[var12 + 0 + (var11 + 0) * var7];
				int var14 = var9[var12 + 2 + (var11 + 0) * var7];
				int var15 = var9[var12 + 0 + (var11 + 2) * var7];
				int var16 = var9[var12 + 2 + (var11 + 2) * var7];
				int var17 = var9[var12 + 1 + (var11 + 1) * var7];
				this.initChunkSeed(var12 + par1, var11 + par2);

				if ((var13 > var17 || var14 > var17 || var15 > var17 || var16 > var17))
				{
					int var18 = 1;
					int var19 = 1;

					if (var13 != 0 && this.nextInt(var18++) == 0)
						var19 = var13+1;

					if (var14 != 0 && this.nextInt(var18++) == 0)
						var19 = var14+1;

					if (var15 != 0 && this.nextInt(var18++) == 0)
						var19 = var15+1;

					if (var16 != 0 && this.nextInt(var18++) == 0)
						var19 = var16+1;

					if (this.nextInt(3) == 0 && var19 <= GenRainLayerTFC.WET)
						outCache[var12 + var11 * par3] = var19;
					else
						outCache[var12 + var11 * par3] = var17;
				}
				else if ((var13 < var17 || var14 < var17 || var15 < var17 || var16 < var17))
				{
					int var18 = 1;
					int var19 = 1;

					if (var13 != 0 && this.nextInt(var18++) == 0)
						var19 = var13-1;

					if (var14 != 0 && this.nextInt(var18++) == 0)
						var19 = var14-1;

					if (var15 != 0 && this.nextInt(var18++) == 0)
						var19 = var15-1;

					if (var16 != 0 && this.nextInt(var18++) == 0)
						var19 = var16-1;

					if (this.nextInt(3) == 0 && var19 >= GenRainLayerTFC.DRY)
						outCache[var12 + var11 * par3] = var19;
					else
						outCache[var12 + var11 * par3] = var17;
				}
				else
				{
					outCache[var12 + var11 * par3] = var17;
				}
			}
		}
		return outCache;
	}
}
