package TFC.WorldGen.GenLayers;

import net.minecraft.world.WorldType;
import net.minecraft.world.gen.layer.GenLayer;
import net.minecraft.world.gen.layer.IntCache;
import TFC.WorldGen.DataLayer;

public class GenLayerRainAmount extends GenLayerTFC
{
	public static DataLayer[] biomeArray = new DataLayer[]{
		DataLayer.Rain_62_5, DataLayer.Rain_125, DataLayer.Rain_250, DataLayer.Rain_500,
		DataLayer.Rain_2000, DataLayer.Rain_4000, DataLayer.Rain_8000, DataLayer.Rain_500,
		DataLayer.Rain_2000, DataLayer.Rain_4000, DataLayer.Rain_8000};

	/** this sets all the biomes that are allowed to appear in the overworld */
	private DataLayer[] allowedBiomes;

	public GenLayerRainAmount(long par1, GenLayer par3GenLayer, WorldType par4WorldType)
	{
		super(par1);
		this.allowedBiomes = biomeArray;
		this.parent = (GenLayerTFC) par3GenLayer;
	}

	/**
	 * Returns a list of integer values generated by this layer. These may be interpreted as temperatures, rainfall
	 * amounts, or biomeList[] indices based on the particular GenLayer subclass.
	 */
	public int[] getInts(int par1, int par2, int par3, int par4)
	{
		int[] var5 = this.parent.getInts(par1, par2, par3, par4);
		int[] var6 = IntCache.getIntCache(par3 * par4);

		for (int var7 = 0; var7 < par4; ++var7)
		{
			for (int var8 = 0; var8 < par3; ++var8)
			{
				this.initChunkSeed((long)(var8 + par1), (long)(var7 + par2));
				int var9 = var5[var8 + var7 * par3];

				if (var9 == 0)
					var6[var8 + var7 * par3] = this.allowedBiomes[this.nextInt(this.allowedBiomes.length)].ID;
				else
					var6[var8 + var7 * par3] = DataLayer.Rain_1000.ID;
			}
		}
		return var6;
	}
}
