package com.bioxx.tfc.WorldGen.GenLayers.Biome;

import net.minecraft.world.gen.layer.IntCache;

import com.bioxx.tfc.WorldGen.TFCBiome;
import com.bioxx.tfc.WorldGen.GenLayers.GenLayerTFC;

public class GenLayerDeepOcean extends GenLayerTFC
{
	public GenLayerDeepOcean(long seed, GenLayerTFC parent)
	{
		super(seed);
		this.parent = parent;
	}

	/**
	 * Returns a list of integer values generated by this layer. These may be interpreted as temperatures, rainfall
	 * amounts, or biomeList[] indices based on the particular GenLayer subclass.
	 */
	@Override
	public int[] getInts(int par1, int par2, int par3, int par4)
	{
		int i1 = par1 - 1;
		int j1 = par2 - 1;
		int k1 = par3 + 2;
		int l1 = par4 + 2;
		int thisID;
		int[] aint = this.parent.getInts(i1, j1, k1, l1);
		int[] outCache = IntCache.getIntCache(par3 * par4);

		for (int i2 = 0; i2 < par4; ++i2)
		{
			for (int j2 = 0; j2 < par3; ++j2)
			{
				int k2 = aint[j2 + 1 + (i2 + 1 - 1) * (par3 + 2)];
				int l2 = aint[j2 + 1 + 1 + (i2 + 1) * (par3 + 2)];
				int i3 = aint[j2 + 1 - 1 + (i2 + 1) * (par3 + 2)];
				int j3 = aint[j2 + 1 + (i2 + 1 + 1) * (par3 + 2)];
				thisID = aint[j2 + 1 + (i2 + 1) * k1];
				int l3 = 0;

				if (k2 == 0)
				{
					++l3;
				}

				if (l2 == 0)
				{
					++l3;
				}

				if (i3 == 0)
				{
					++l3;
				}

				if (j3 == 0)
				{
					++l3;
				}

				if (thisID == 0 && l3 > 3)
				{
					outCache[j2 + i2 * par3] = TFCBiome.DeepOcean.biomeID;
				}
				else
				{
					outCache[j2 + i2 * par3] = thisID;
				}
			}
		}



		return outCache;
	}
}
