package net.minecraft.src;

public class GenLayerRiverMixTFC extends GenLayer
{
	private GenLayer field_35512_b;
	private GenLayer field_35513_c;

	public GenLayerRiverMixTFC(long par1, GenLayer par3GenLayer, GenLayer par4GenLayer)
	{
		super(par1);
		this.field_35512_b = par3GenLayer;
		this.field_35513_c = par4GenLayer;
	}

	/**
	 * Returns a list of integer values generated by this layer. These may be interpreted as temperatures, rainfall
	 * amounts, or biomeList[] indices based on the particular GenLayer subclass.
	 */
	public int[] getInts(int par1, int par2, int par3, int par4)
	{
		int[] layerBiomes = this.field_35512_b.getInts(par1, par2, par3, par4);
		int[] layerRivers = this.field_35513_c.getInts(par1, par2, par3, par4);
		int[] layerOut = IntCache.getIntCache(par3 * par4);

		for (int var8 = 0; var8 < par3 * par4; ++var8)
		{
			int b = layerBiomes[var8];
			int r = layerRivers[var8];

			if (layerBiomes[var8] == BiomeGenBase.ocean.biomeID)
			{
				layerOut[var8] = layerBiomes[var8];
			}
			else if (layerRivers[var8] >= 0)
			{
				if (layerBiomes[var8] == BiomeGenBase.icePlains.biomeID)
				{
					layerOut[var8] = BiomeGenBase.frozenRiver.biomeID;
				}
				else if(layerBiomes[var8] == BiomeGenBase.swampland.biomeID)
				{
					layerOut[var8] = BiomeGenBase.river2.biomeID;
				}
				else if(layerBiomes[var8] == BiomeGenBase.swamp2.biomeID)
				{
					layerOut[var8] = BiomeGenBase.river3.biomeID;
				}
				else if(layerBiomes[var8] == BiomeGenBase.swamp3.biomeID)
				{
					layerOut[var8] = BiomeGenBase.river4.biomeID;
				}
				else if(layerBiomes[var8] == BiomeGenBase.swamp4.biomeID)
				{
					layerOut[var8] = BiomeGenBase.river5.biomeID;
				}
				else if(layerBiomes[var8] == BiomeGenBase.swamp5.biomeID)
				{
					layerOut[var8] = BiomeGenBase.river6.biomeID;
				}
				else if(layerBiomes[var8] == BiomeGenBase.swamp6.biomeID)
				{
					layerOut[var8] = BiomeGenBase.river7.biomeID;
				}
				else if(layerBiomes[var8] == BiomeGenBase.swamp7.biomeID)
				{
					layerOut[var8] = BiomeGenBase.river8.biomeID;
				}
				else if(layerBiomes[var8] == BiomeGenBase.swamp9.biomeID)
				{
					layerOut[var8] = BiomeGenBase.river10.biomeID;
				}
				else if(layerBiomes[var8] == BiomeGenBase.swamp10.biomeID)
				{
					layerOut[var8] = BiomeGenBase.river11.biomeID;
				}
				else if(layerBiomes[var8] == BiomeGenBase.taiga.biomeID)
				{
					layerOut[var8] = BiomeGenBase.river12.biomeID;
				}
				else if(layerBiomes[var8] == BiomeGenBase.taiga2.biomeID)
				{
					layerOut[var8] = BiomeGenBase.river13.biomeID;
				}
				else if(layerBiomes[var8] == BiomeGenBase.taiga3.biomeID)
				{
					layerOut[var8] = BiomeGenBase.river14.biomeID;
				}
				else if(layerBiomes[var8] == BiomeGenBase.taiga4.biomeID)
				{
					layerOut[var8] = BiomeGenBase.river15.biomeID;
				}
				else if(layerBiomes[var8] == BiomeGenBase.taiga5.biomeID)
				{
					layerOut[var8] = BiomeGenBase.river16.biomeID;
				}
				else if(layerBiomes[var8] == BiomeGenBase.taiga6.biomeID)
				{
					layerOut[var8] = BiomeGenBase.river17.biomeID;
				}
				else if(layerBiomes[var8] == BiomeGenBase.taiga7.biomeID)
				{
					layerOut[var8] = BiomeGenBase.river18.biomeID;
				}
				else if(layerBiomes[var8] == BiomeGenBase.taiga8.biomeID)
				{
					layerOut[var8] = BiomeGenBase.river19.biomeID;
				}
				else if(layerBiomes[var8] == BiomeGenBase.taiga9.biomeID)
				{
					layerOut[var8] = BiomeGenBase.river20.biomeID;
				}
				else if(layerBiomes[var8] == BiomeGenBase.taiga10.biomeID)
				{
					layerOut[var8] = BiomeGenBase.river21.biomeID;
				}
				else if(layerBiomes[var8] == BiomeGenBase.forest.biomeID)
				{
					layerOut[var8] = BiomeGenBase.river22.biomeID;
				}
				else if(layerBiomes[var8] == BiomeGenBase.forest2.biomeID)
				{
					layerOut[var8] = BiomeGenBase.river23.biomeID;
				}
				else if(layerBiomes[var8] == BiomeGenBase.forest3.biomeID)
				{
					layerOut[var8] = BiomeGenBase.river24.biomeID;
				}
				else if(layerBiomes[var8] == BiomeGenBase.forest4.biomeID)
				{
					layerOut[var8] = BiomeGenBase.river25.biomeID;
				}
				else if(layerBiomes[var8] == BiomeGenBase.forest5.biomeID)
				{
					layerOut[var8] = BiomeGenBase.river26.biomeID;
				}
				else if(layerBiomes[var8] == BiomeGenBase.forest6.biomeID)
				{
					layerOut[var8] = BiomeGenBase.river27.biomeID;
				}
				else if(layerBiomes[var8] == BiomeGenBase.forest7.biomeID)
				{
					layerOut[var8] = BiomeGenBase.river28.biomeID;
				}
				else if(layerBiomes[var8] == BiomeGenBase.forest8.biomeID)
				{
					layerOut[var8] = BiomeGenBase.river29.biomeID;
				}
				else if(layerBiomes[var8] == BiomeGenBase.forest9.biomeID)
				{
					layerOut[var8] = BiomeGenBase.river30.biomeID;
				}
				else if(layerBiomes[var8] == BiomeGenBase.plains.biomeID)
				{
					layerOut[var8] = BiomeGenBase.river31.biomeID;
				}
				else if(layerBiomes[var8] == BiomeGenBase.plains2.biomeID)
				{
					layerOut[var8] = BiomeGenBase.river32.biomeID;
				}
				else if(layerBiomes[var8] == BiomeGenBase.plains3.biomeID)
				{
					layerOut[var8] = BiomeGenBase.river33.biomeID;
				}
				else if(layerBiomes[var8] == BiomeGenBase.plains4.biomeID)
				{
					layerOut[var8] = BiomeGenBase.river34.biomeID;
				}
				else if(layerBiomes[var8] == BiomeGenBase.plains5.biomeID)
				{
					layerOut[var8] = BiomeGenBase.river35.biomeID;
				}
				else if(layerBiomes[var8] == BiomeGenBase.plains6.biomeID)
				{
					layerOut[var8] = BiomeGenBase.river36.biomeID;
				}
				else if(layerBiomes[var8] == BiomeGenBase.plains7.biomeID)
				{
					layerOut[var8] = BiomeGenBase.river37.biomeID;
				}
				else if(layerBiomes[var8] == BiomeGenBase.plains8.biomeID)
				{
					layerOut[var8] = BiomeGenBase.river38.biomeID;
				}
				else if(layerBiomes[var8] == BiomeGenBase.plains9.biomeID)
				{
					layerOut[var8] = BiomeGenBase.river39.biomeID;
				}
				else if(layerBiomes[var8] == BiomeGenBase.plains10.biomeID)
				{
					layerOut[var8] = BiomeGenBase.river40.biomeID;
				}
				else if(layerBiomes[var8] == BiomeGenBase.extremeHills.biomeID)
				{
					layerOut[var8] = BiomeGenBase.extremeHills.biomeID;
				}
				else if(layerBiomes[var8] == BiomeGenBase.hills2.biomeID)
				{
					layerOut[var8] = BiomeGenBase.hills2.biomeID;
				}
				else if(layerBiomes[var8] == BiomeGenBase.hills3.biomeID)
				{
					layerOut[var8] = BiomeGenBase.hills3.biomeID;
				}
				else if(layerBiomes[var8] == BiomeGenBase.hills4.biomeID)
				{
					layerOut[var8] = BiomeGenBase.hills4.biomeID;
				}
				else if(layerBiomes[var8] == BiomeGenBase.hills5.biomeID)
				{
					layerOut[var8] = BiomeGenBase.hills5.biomeID;
				}
				else if(layerBiomes[var8] == BiomeGenBase.hills6.biomeID)
				{
					layerOut[var8] = BiomeGenBase.hills6.biomeID;
				}
				else if(layerBiomes[var8] == BiomeGenBase.hills7.biomeID)
				{
					layerOut[var8] = BiomeGenBase.hills7.biomeID;
				}
				else if(layerBiomes[var8] == BiomeGenBase.hills8.biomeID)
				{
					layerOut[var8] = BiomeGenBase.hills8.biomeID;
				}
				else if(layerBiomes[var8] == BiomeGenBase.hills9.biomeID)
				{
					layerOut[var8] = BiomeGenBase.hills9.biomeID;
				}
				else if(layerBiomes[var8] == BiomeGenBase.hills10.biomeID)
				{
					layerOut[var8] = BiomeGenBase.hills10.biomeID;
				}
				else if(layerBiomes[var8] == BiomeGenBase.desert.biomeID)
				{
					layerOut[var8] = BiomeGenBase.river51.biomeID;
				}
				else if(layerBiomes[var8] == BiomeGenBase.desert2.biomeID)
				{
					layerOut[var8] = BiomeGenBase.river52.biomeID;
				}
				else if(layerBiomes[var8] == BiomeGenBase.desert3.biomeID)
				{
					layerOut[var8] = BiomeGenBase.river53.biomeID;
				}
				else if(layerBiomes[var8] == BiomeGenBase.desert4.biomeID)
				{
					layerOut[var8] = BiomeGenBase.river54.biomeID;
				}
				else if(layerBiomes[var8] == BiomeGenBase.desert5.biomeID)
				{
					layerOut[var8] = BiomeGenBase.river55.biomeID;
				}
				else if(layerBiomes[var8] == BiomeGenBase.desert6.biomeID)
				{
					layerOut[var8] = BiomeGenBase.river56.biomeID;
				}
				else if(layerBiomes[var8] == BiomeGenBase.desert7.biomeID)
				{
					layerOut[var8] = BiomeGenBase.river57.biomeID;
				}
				else if(layerBiomes[var8] == BiomeGenBase.desert8.biomeID)
				{
					layerOut[var8] = BiomeGenBase.river58.biomeID;
				}
				else if(layerBiomes[var8] == BiomeGenBase.desert9.biomeID)
				{
					layerOut[var8] = BiomeGenBase.river59.biomeID;
				}
				else if(layerBiomes[var8] == BiomeGenBase.extremeHillsEdge.biomeID)
				{
					layerOut[var8] = BiomeGenBase.extremeHillsEdge.biomeID;
				}
				else if(layerBiomes[var8] == BiomeGenBase.HillsEdge2.biomeID)
				{
					layerOut[var8] = BiomeGenBase.HillsEdge2.biomeID;
				}
				else if(layerBiomes[var8] == BiomeGenBase.HillsEdge3.biomeID)
				{
					layerOut[var8] = BiomeGenBase.HillsEdge3.biomeID;
				}
				else if(layerBiomes[var8] == BiomeGenBase.HillsEdge4.biomeID)
				{
					layerOut[var8] = BiomeGenBase.HillsEdge4.biomeID;
				}
				else if(layerBiomes[var8] == BiomeGenBase.HillsEdge5.biomeID)
				{
					layerOut[var8] = BiomeGenBase.HillsEdge5.biomeID;
				}
				else if(layerBiomes[var8] == BiomeGenBase.HillsEdge6.biomeID)
				{
					layerOut[var8] = BiomeGenBase.HillsEdge6.biomeID;
				}
				else if(layerBiomes[var8] == BiomeGenBase.HillsEdge7.biomeID)
				{
					layerOut[var8] = BiomeGenBase.HillsEdge7.biomeID;
				}
				else if(layerBiomes[var8] == BiomeGenBase.HillsEdge8.biomeID)
				{
					layerOut[var8] = BiomeGenBase.HillsEdge8.biomeID;
				}
				else if(layerBiomes[var8] == BiomeGenBase.HillsEdge9.biomeID)
				{
					layerOut[var8] = BiomeGenBase.HillsEdge9.biomeID;
				}
				else if(layerBiomes[var8] == BiomeGenBase.HillsEdge10.biomeID)
				{
					layerOut[var8] = BiomeGenBase.HillsEdge10.biomeID;
				}
				else if (layerBiomes[var8] != BiomeGenBase.mushroomIsland.biomeID && layerBiomes[var8] != BiomeGenBase.mushroomIslandShore.biomeID)
				{
					layerOut[var8] = layerRivers[var8];
				}
				else
				{
					layerOut[var8] = BiomeGenBase.mushroomIslandShore.biomeID;
				}
			}
			else
			{
				layerOut[var8] = layerBiomes[var8];
			}

			//            if(layerOut[var8] == 7)
				//            	System.out.println("Made a Normal River");
		}

		return layerOut;
	}

	/**
	 * Initialize layer's local worldGenSeed based on its own baseSeed and the world's global seed (passed in as an
	 * argument).
	 */
	public void initWorldGenSeed(long par1)
	{
		this.field_35512_b.initWorldGenSeed(par1);
		this.field_35513_c.initWorldGenSeed(par1);
		super.initWorldGenSeed(par1);
	}
}
