package net.minecraft.src;

public class GenLayerSwampRiversTFC extends GenLayer
{
	public GenLayerSwampRiversTFC(long par1, GenLayer par3GenLayer)
	{
		super(par1);
		this.parent = par3GenLayer;
	}

	/**
	 * Returns a list of integer values generated by this layer. These may be interpreted as temperatures, rainfall
	 * amounts, or biomeList[] indices based on the particular GenLayer subclass.
	 */
	public int[] getInts(int par1, int par2, int par3, int par4)
	{
		int[] var5 = this.parent.getInts(par1 - 1, par2 - 1, par3 + 2, par4 + 2);
		int[] var6 = IntCache.getIntCache(par3 * par4);

		for (int var7 = 0; var7 < par4; ++var7)
		{
			for (int var8 = 0; var8 < par3; ++var8)
			{
				this.initChunkSeed((long)(var8 + par1), (long)(var7 + par2));
				int var9 = var5[var8 + 1 + (var7 + 1) * (par3 + 2)];

				if(var9 == BiomeGenBase.swampland.biomeID && this.nextInt(6) == 0)
				{
					var6[var8 + var7 * par3] = BiomeGenBase.river2.biomeID;
				}
				else if(var9 == BiomeGenBase.swamp2.biomeID && this.nextInt(6) == 0)
				{
					var6[var8 + var7 * par3] = BiomeGenBase.river3.biomeID;
				}
				else if(var9 == BiomeGenBase.swamp3.biomeID && this.nextInt(6) == 0)
				{
					var6[var8 + var7 * par3] = BiomeGenBase.river4.biomeID;
				}
				else if(var9 == BiomeGenBase.swamp4.biomeID && this.nextInt(6) == 0)
				{
					var6[var8 + var7 * par3] = BiomeGenBase.river5.biomeID;
				}
				else if(var9 == BiomeGenBase.swamp5.biomeID && this.nextInt(6) == 0)
				{
					var6[var8 + var7 * par3] = BiomeGenBase.river6.biomeID;
				}
				else if(var9 == BiomeGenBase.swamp6.biomeID && this.nextInt(6) == 0)
				{
					var6[var8 + var7 * par3] = BiomeGenBase.river7.biomeID;
				}
				else if(var9 == BiomeGenBase.swamp7.biomeID && this.nextInt(6) == 0)
				{
					var6[var8 + var7 * par3] = BiomeGenBase.river8.biomeID;
				}
				else if(var9 == BiomeGenBase.swamp9.biomeID && this.nextInt(6) == 0)
				{
					var6[var8 + var7 * par3] = BiomeGenBase.river10.biomeID;
				}
				else if(var9 == BiomeGenBase.swamp10.biomeID && this.nextInt(6) == 0)
				{
					var6[var8 + var7 * par3] = BiomeGenBase.river11.biomeID;
				}
				else if(var9 == BiomeGenBase.taiga.biomeID && this.nextInt(6) == 0)
				{
					var6[var8 + var7 * par3] = BiomeGenBase.river12.biomeID;
				}
				else if(var9 == BiomeGenBase.taiga2.biomeID && this.nextInt(6) == 0)
				{
					var6[var8 + var7 * par3] = BiomeGenBase.river13.biomeID;
				}
				else if(var9 == BiomeGenBase.taiga3.biomeID && this.nextInt(6) == 0)
				{
					var6[var8 + var7 * par3] = BiomeGenBase.river14.biomeID;
				}
				else if(var9 == BiomeGenBase.taiga4.biomeID && this.nextInt(6) == 0)
				{
					var6[var8 + var7 * par3] = BiomeGenBase.river15.biomeID;
				}
				else if(var9 == BiomeGenBase.taiga5.biomeID && this.nextInt(6) == 0)
				{
					var6[var8 + var7 * par3] = BiomeGenBase.river16.biomeID;
				}
				else if(var9 == BiomeGenBase.taiga6.biomeID && this.nextInt(6) == 0)
				{
					var6[var8 + var7 * par3] = BiomeGenBase.river17.biomeID;
				}
				else if(var9 == BiomeGenBase.taiga7.biomeID && this.nextInt(6) == 0)
				{
					var6[var8 + var7 * par3] = BiomeGenBase.river18.biomeID;
				}
				else if(var9 == BiomeGenBase.taiga8.biomeID && this.nextInt(6) == 0)
				{
					var6[var8 + var7 * par3] = BiomeGenBase.river19.biomeID;
				}
				else if(var9 == BiomeGenBase.taiga9.biomeID && this.nextInt(6) == 0)
				{
					var6[var8 + var7 * par3] = BiomeGenBase.river20.biomeID;
				}
				else if(var9 == BiomeGenBase.taiga10.biomeID && this.nextInt(6) == 0)
				{
					var6[var8 + var7 * par3] = BiomeGenBase.river21.biomeID;
				}
				else if(var9 == BiomeGenBase.forest.biomeID && this.nextInt(6) == 0)
				{
					var6[var8 + var7 * par3] = BiomeGenBase.river22.biomeID;
				}
				else if(var9 == BiomeGenBase.forest2.biomeID && this.nextInt(6) == 0)
				{
					var6[var8 + var7 * par3] = BiomeGenBase.river23.biomeID;
				}
				else if(var9 == BiomeGenBase.forest3.biomeID && this.nextInt(6) == 0)
				{
					var6[var8 + var7 * par3] = BiomeGenBase.river24.biomeID;
				}
				else if(var9 == BiomeGenBase.forest4.biomeID && this.nextInt(6) == 0)
				{
					var6[var8 + var7 * par3] = BiomeGenBase.river25.biomeID;
				}
				else if(var9 == BiomeGenBase.forest5.biomeID && this.nextInt(6) == 0)
				{
					var6[var8 + var7 * par3] = BiomeGenBase.river26.biomeID;
				}
				else if(var9 == BiomeGenBase.forest6.biomeID && this.nextInt(6) == 0)
				{
					var6[var8 + var7 * par3] = BiomeGenBase.river27.biomeID;
				}
				else if(var9 == BiomeGenBase.forest7.biomeID && this.nextInt(6) == 0)
				{
					var6[var8 + var7 * par3] = BiomeGenBase.river28.biomeID;
				}
				else if(var9 == BiomeGenBase.forest8.biomeID && this.nextInt(6) == 0)
				{
					var6[var8 + var7 * par3] = BiomeGenBase.river29.biomeID;
				}
				else if(var9 == BiomeGenBase.forest9.biomeID && this.nextInt(6) == 0)
				{
					var6[var8 + var7 * par3] = BiomeGenBase.river30.biomeID;
				}
				else if(var9 == BiomeGenBase.plains.biomeID && this.nextInt(6) == 0)
				{
					var6[var8 + var7 * par3] = BiomeGenBase.river31.biomeID;
				}
				else if(var9 == BiomeGenBase.plains2.biomeID && this.nextInt(6) == 0)
				{
					var6[var8 + var7 * par3] = BiomeGenBase.river32.biomeID;
				}
				else if(var9 == BiomeGenBase.plains3.biomeID && this.nextInt(6) == 0)
				{
					var6[var8 + var7 * par3] = BiomeGenBase.river33.biomeID;
				}
				else if(var9 == BiomeGenBase.plains4.biomeID && this.nextInt(6) == 0)
				{
					var6[var8 + var7 * par3] = BiomeGenBase.river34.biomeID;
				}
				else if(var9 == BiomeGenBase.plains5.biomeID && this.nextInt(6) == 0)
				{
					var6[var8 + var7 * par3] = BiomeGenBase.river35.biomeID;
				}
				else if(var9 == BiomeGenBase.plains6.biomeID && this.nextInt(6) == 0)
				{
					var6[var8 + var7 * par3] = BiomeGenBase.river36.biomeID;
				}
				else if(var9 == BiomeGenBase.plains7.biomeID && this.nextInt(6) == 0)
				{
					var6[var8 + var7 * par3] = BiomeGenBase.river37.biomeID;
				}
				else if(var9 == BiomeGenBase.plains8.biomeID && this.nextInt(6) == 0)
				{
					var6[var8 + var7 * par3] = BiomeGenBase.river38.biomeID;
				}
				else if(var9 == BiomeGenBase.plains9.biomeID && this.nextInt(6) == 0)
				{
					var6[var8 + var7 * par3] = BiomeGenBase.river39.biomeID;
				}
				else if(var9 == BiomeGenBase.plains10.biomeID && this.nextInt(6) == 0)
				{
					var6[var8 + var7 * par3] = BiomeGenBase.river40.biomeID;
				}
				else
				{
					var6[var8 + var7 * par3] = var9;
				}
			}
		}

		return var6;
	}
}
