package net.minecraft.src;

public class GenLayerShoreTFC extends GenLayer
{
	public GenLayerShoreTFC(long par1, GenLayer par3GenLayer)
	{
		super(par1);
		this.parent = par3GenLayer;
	}

	/**
	 * Returns a list of integer values generated by this layer. These may be interpreted as temperatures, rainfall
	 * amounts, or biomeList[] indices based on the particular GenLayer subclass.
	 */
	public int[] getInts(int par1, int par2, int par3, int par4)
	{
		int[] var5 = this.parent.getInts(par1 - 1, par2 - 1, par3 + 2, par4 + 2);
		int[] var6 = IntCache.getIntCache(par3 * par4);

		for (int var7 = 0; var7 < par4; ++var7)
		{
			for (int var8 = 0; var8 < par3; ++var8)
			{
				this.initChunkSeed((long)(var8 + par1), (long)(var7 + par2));
				int var9 = var5[var8 + 1 + (var7 + 1) * (par3 + 2)];
				int var10;
				int var11;
				int var12;
				int var13;

				if (var9 == BiomeGenBase.mushroomIsland.biomeID)
				{
					var10 = var5[var8 + 1 + (var7 + 1 - 1) * (par3 + 2)];
					var11 = var5[var8 + 1 + 1 + (var7 + 1) * (par3 + 2)];
					var12 = var5[var8 + 1 - 1 + (var7 + 1) * (par3 + 2)];
					var13 = var5[var8 + 1 + (var7 + 1 + 1) * (par3 + 2)];

					if (var10 != BiomeGenBase.ocean.biomeID && var11 != BiomeGenBase.ocean.biomeID && var12 != BiomeGenBase.ocean.biomeID && var13 != BiomeGenBase.ocean.biomeID)
					{
						var6[var8 + var7 * par3] = var9;
					}
					else
					{
						var6[var8 + var7 * par3] = BiomeGenBase.mushroomIslandShore.biomeID;
					}
				}
				else if (var9 != BiomeGenBase.ocean.biomeID && var9 != BiomeGenBase.river.biomeID && var9 != BiomeGenBase.swampland.biomeID && var9 != BiomeGenBase.extremeHills.biomeID &&
						!(var9 == BiomeGenBase.swamp10.biomeID || var9 == BiomeGenBase.swamp2.biomeID || var9 == BiomeGenBase.swamp3.biomeID || 
						var9 == BiomeGenBase.swamp4.biomeID || var9 == BiomeGenBase.swamp5.biomeID || var9 == BiomeGenBase.swamp6.biomeID || var9 == BiomeGenBase.swamp7.biomeID ||
						var9 == BiomeGenBase.swamp8.biomeID || var9 == BiomeGenBase.swamp9.biomeID) && !(var9 == BiomeGenBase.hills2.biomeID || var9 == BiomeGenBase.hills3.biomeID || 
						var9 == BiomeGenBase.hills4.biomeID || 
						var9 == BiomeGenBase.hills5.biomeID || var9 == BiomeGenBase.hills6.biomeID || var9 == BiomeGenBase.hills7.biomeID || var9 == BiomeGenBase.hills8.biomeID ||
						var9 == BiomeGenBase.hills9.biomeID || var9 == BiomeGenBase.hills10.biomeID) && 
						!(var9 != BiomeGenBase.river2.biomeID || var9 != BiomeGenBase.river3.biomeID ||var9 != BiomeGenBase.river3.biomeID ||var9 != BiomeGenBase.river4.biomeID ||
						var9 != BiomeGenBase.river5.biomeID ||var9 != BiomeGenBase.river6.biomeID ||var9 != BiomeGenBase.river7.biomeID ||var9 != BiomeGenBase.river8.biomeID ||
						var9 != BiomeGenBase.river9.biomeID ||var9 != BiomeGenBase.river10.biomeID ||var9 != BiomeGenBase.river11.biomeID ||var9 != BiomeGenBase.river12.biomeID ||
						var9 != BiomeGenBase.river13.biomeID ||var9 != BiomeGenBase.river14.biomeID ||var9 != BiomeGenBase.river15.biomeID ||var9 != BiomeGenBase.river16.biomeID ||
						var9 != BiomeGenBase.river17.biomeID ||var9 != BiomeGenBase.river18.biomeID ||var9 != BiomeGenBase.river19.biomeID ||var9 != BiomeGenBase.river20.biomeID ||
						var9 != BiomeGenBase.river21.biomeID ||var9 != BiomeGenBase.river22.biomeID ||var9 != BiomeGenBase.river23.biomeID ||var9 != BiomeGenBase.river24.biomeID ||
						var9 != BiomeGenBase.river25.biomeID ||var9 != BiomeGenBase.river26.biomeID ||var9 != BiomeGenBase.river27.biomeID ||var9 != BiomeGenBase.river28.biomeID ||
						var9 != BiomeGenBase.river29.biomeID ||var9 != BiomeGenBase.river30.biomeID ||var9 != BiomeGenBase.river31.biomeID ||var9 != BiomeGenBase.river32.biomeID ||
						var9 != BiomeGenBase.river33.biomeID ||var9 != BiomeGenBase.river34.biomeID ||var9 != BiomeGenBase.river35.biomeID ||var9 != BiomeGenBase.river36.biomeID ||
						var9 != BiomeGenBase.river37.biomeID ||var9 != BiomeGenBase.river38.biomeID ||var9 != BiomeGenBase.river39.biomeID ||var9 != BiomeGenBase.river40.biomeID ||
						var9 != BiomeGenBase.river41.biomeID ||var9 != BiomeGenBase.river42.biomeID ||var9 != BiomeGenBase.river43.biomeID ||var9 != BiomeGenBase.river44.biomeID ||
						var9 != BiomeGenBase.river45.biomeID ||var9 != BiomeGenBase.river46.biomeID ||var9 != BiomeGenBase.river47.biomeID ||var9 != BiomeGenBase.river48.biomeID ||
						var9 != BiomeGenBase.river49.biomeID ||var9 != BiomeGenBase.river50.biomeID ||var9 != BiomeGenBase.river51.biomeID ||var9 != BiomeGenBase.river52.biomeID ||
						var9 != BiomeGenBase.river53.biomeID ||var9 != BiomeGenBase.river54.biomeID ||var9 != BiomeGenBase.river55.biomeID ||var9 != BiomeGenBase.river56.biomeID ||
						var9 != BiomeGenBase.river57.biomeID ||var9 != BiomeGenBase.river58.biomeID ||var9 != BiomeGenBase.river59.biomeID))
				{
					var10 = var5[var8 + 1 + (var7 + 1 - 1) * (par3 + 2)];
					var11 = var5[var8 + 1 + 1 + (var7 + 1) * (par3 + 2)];
					var12 = var5[var8 + 1 - 1 + (var7 + 1) * (par3 + 2)];
					var13 = var5[var8 + 1 + (var7 + 1 + 1) * (par3 + 2)];

					if (var10 != BiomeGenBase.ocean.biomeID && var11 != BiomeGenBase.ocean.biomeID && var12 != BiomeGenBase.ocean.biomeID && var13 != BiomeGenBase.ocean.biomeID)
					{
						var6[var8 + var7 * par3] = var9;
					}
					else
					{
						var6[var8 + var7 * par3] = BiomeGenBase.beach.biomeID;
					}
				}
				else if (var9 == BiomeGenBase.extremeHills.biomeID || var9 == BiomeGenBase.hills2.biomeID || var9 == BiomeGenBase.hills3.biomeID || 
						var9 == BiomeGenBase.hills4.biomeID || 
						var9 == BiomeGenBase.hills5.biomeID || var9 == BiomeGenBase.hills6.biomeID || var9 == BiomeGenBase.hills7.biomeID || var9 == BiomeGenBase.hills8.biomeID ||
						var9 == BiomeGenBase.hills9.biomeID || var9 == BiomeGenBase.hills10.biomeID)
				{
					var10 = var5[var8 + 1 + (var7 + 1 - 1) * (par3 + 2)];
					var11 = var5[var8 + 1 + 1 + (var7 + 1) * (par3 + 2)];
					var12 = var5[var8 + 1 - 1 + (var7 + 1) * (par3 + 2)];
					var13 = var5[var8 + 1 + (var7 + 1 + 1) * (par3 + 2)];

					if (var10 == BiomeGenBase.extremeHills.biomeID && var11 == BiomeGenBase.extremeHills.biomeID && var12 == BiomeGenBase.extremeHills.biomeID && var13 == BiomeGenBase.extremeHills.biomeID||
							var10 == BiomeGenBase.hills2.biomeID && var11 == BiomeGenBase.hills2.biomeID && var12 == BiomeGenBase.hills2.biomeID && var13 == BiomeGenBase.hills2.biomeID ||
							var10 == BiomeGenBase.hills3.biomeID && var11 == BiomeGenBase.hills3.biomeID && var12 == BiomeGenBase.hills3.biomeID && var13 == BiomeGenBase.hills3.biomeID ||
							var10 == BiomeGenBase.hills4.biomeID && var11 == BiomeGenBase.hills4.biomeID && var12 == BiomeGenBase.hills4.biomeID && var13 == BiomeGenBase.hills4.biomeID ||
							var10 == BiomeGenBase.hills5.biomeID && var11 == BiomeGenBase.hills5.biomeID && var12 == BiomeGenBase.hills5.biomeID && var13 == BiomeGenBase.hills5.biomeID ||
							var10 == BiomeGenBase.hills6.biomeID && var11 == BiomeGenBase.hills6.biomeID && var12 == BiomeGenBase.hills6.biomeID && var13 == BiomeGenBase.hills6.biomeID ||
							var10 == BiomeGenBase.hills7.biomeID && var11 == BiomeGenBase.hills7.biomeID && var12 == BiomeGenBase.hills7.biomeID && var13 == BiomeGenBase.hills7.biomeID ||
							var10 == BiomeGenBase.hills8.biomeID && var11 == BiomeGenBase.hills8.biomeID && var12 == BiomeGenBase.hills8.biomeID && var13 == BiomeGenBase.hills8.biomeID ||
							var10 == BiomeGenBase.hills9.biomeID && var11 == BiomeGenBase.hills9.biomeID && var12 == BiomeGenBase.hills9.biomeID && var13 == BiomeGenBase.hills9.biomeID ||
							var10 == BiomeGenBase.hills10.biomeID && var11 == BiomeGenBase.hills10.biomeID && var12 == BiomeGenBase.hills10.biomeID && var13 == BiomeGenBase.hills10.biomeID)
					{
						var6[var8 + var7 * par3] = var9;
					}
					else if(var10 == BiomeGenBase.hills2.biomeID || var11 == BiomeGenBase.hills2.biomeID || var12 == BiomeGenBase.hills2.biomeID || var13 == BiomeGenBase.hills2.biomeID)
					{
						var6[var8 + var7 * par3] = BiomeGenBase.HillsEdge2.biomeID;
					}
					else if(var10 == BiomeGenBase.hills3.biomeID || var11 == BiomeGenBase.hills3.biomeID || var12 == BiomeGenBase.hills3.biomeID || var13 == BiomeGenBase.hills3.biomeID)
					{
						var6[var8 + var7 * par3] = BiomeGenBase.HillsEdge3.biomeID;
					}
					else if(var10 == BiomeGenBase.hills4.biomeID || var11 == BiomeGenBase.hills4.biomeID || var12 == BiomeGenBase.hills4.biomeID || var13 == BiomeGenBase.hills4.biomeID)
					{
						var6[var8 + var7 * par3] = BiomeGenBase.HillsEdge4.biomeID;
					}
					else if(var10 == BiomeGenBase.hills5.biomeID || var11 == BiomeGenBase.hills5.biomeID || var12 == BiomeGenBase.hills5.biomeID || var13 == BiomeGenBase.hills5.biomeID)
					{
						var6[var8 + var7 * par3] = BiomeGenBase.HillsEdge5.biomeID;
					}
					else if(var10 == BiomeGenBase.hills6.biomeID || var11 == BiomeGenBase.hills6.biomeID || var12 == BiomeGenBase.hills6.biomeID || var13 == BiomeGenBase.hills6.biomeID)
					{
						var6[var8 + var7 * par3] = BiomeGenBase.HillsEdge6.biomeID;
					}
					else if(var10 == BiomeGenBase.hills7.biomeID || var11 == BiomeGenBase.hills7.biomeID || var12 == BiomeGenBase.hills7.biomeID || var13 == BiomeGenBase.hills7.biomeID)
					{
						var6[var8 + var7 * par3] = BiomeGenBase.HillsEdge7.biomeID;
					}
					else if(var10 == BiomeGenBase.hills8.biomeID || var11 == BiomeGenBase.hills8.biomeID || var12 == BiomeGenBase.hills8.biomeID || var13 == BiomeGenBase.hills8.biomeID)
					{
						var6[var8 + var7 * par3] = BiomeGenBase.HillsEdge8.biomeID;
					}
					else if(var10 == BiomeGenBase.hills9.biomeID || var11 == BiomeGenBase.hills9.biomeID || var12 == BiomeGenBase.hills9.biomeID || var13 == BiomeGenBase.hills9.biomeID)
					{
						var6[var8 + var7 * par3] = BiomeGenBase.HillsEdge9.biomeID;
					}
					else if(var10 == BiomeGenBase.hills10.biomeID || var11 == BiomeGenBase.hills10.biomeID || var12 == BiomeGenBase.hills10.biomeID || var13 == BiomeGenBase.hills10.biomeID)
					{
						var6[var8 + var7 * par3] = BiomeGenBase.HillsEdge10.biomeID;
					}
					else
					{
						var6[var8 + var7 * par3] = BiomeGenBase.extremeHillsEdge.biomeID;
					}
				}
				else
				{
					var6[var8 + var7 * par3] = var9;
				}
			}
		}

		return var6;
	}
}
